[workspace]
members = [
  "druid-icon",
  "druid-icon-generator",
  "kiro-synth-core",
  "kiro-synth-engine",
  "kiro-synth-midi",
  "kiro-synth-host",
#  "kiro-synth-nrf52",
#  "nrf52840-mdk"
]

exclude = [
]