[package]
name = "kiro-synth-core"
version = "0.1.0"
authors = ["Christian Perez Llamas"]
edition = "2018"

[dependencies]
num-traits = { version = "0.2", default-features = false, features = ["libm"] }
libm = "0.2.1"
